from fastapi import APIRouter, HTTPException
from app.schemas.otp import OTPRequest, OTPVerifyRequest, OTPTelegramRequest, OTPEmailRequest
from app.services.otp import OTPService
from app.services.totp import TOTPService
from app.schemas.totp import TOTPEnableRequest, TOTPVerifyRequest
from pydantic import BaseModel

router = APIRouter()

@router.post("/send-otp")
async def send_otp(request: OTPRequest):
    result = OTPService.send_otp(request.phone_number)
    return {
        "message": result["message"], 
        "counter": result["counter"],
        "phone_number": request.phone_number
    }

@router.post("/send-sms-otp")
async def send_sms_otp(request: OTPRequest):
    result = OTPService.send_otp_sms(request.phone_number)
    
    if result["status"] == "error":
        raise HTTPException(status_code=500, detail=result["message"])

    return {
        "message": result["message"], 
        "counter": result["counter"],
        "phone_number": request.phone_number
    }



from app.schemas.otp import OTPRequest, OTPVerifyRequest, OTPTelegramRequest, OTPEmailRequest

# ...

@router.post("/send-email-otp")
async def send_email_otp(request: OTPEmailRequest):
    result = OTPService.send_otp_email(request.email)
    
    if result["status"] == "error":
        raise HTTPException(status_code=500, detail=result["message"])

    return {
        "message": result["message"], 
        "counter": result["counter"],
        "email": request.email
    }


@router.post("/verify-otp")
async def verify_otp(request: OTPVerifyRequest):
    is_valid = OTPService.verify_otp(request.identifier, request.otp_code)
    
    if is_valid:
        return {"message": "OTP verified successfully"}
    else:
        raise HTTPException(status_code=400, detail="Invalid or expired OTP")

# --- TOTP (Google Authenticator) Features ---

@router.post("/totp/enable")
async def enable_totp(request: TOTPEnableRequest):
    """Generates a secret and QR code URI for the user to scan."""
    data = TOTPService.generate_totp_secret(request.identifier)
    return data

@router.post("/totp/verify")
async def verify_totp(request: TOTPVerifyRequest):
    """Verifies the code generated by Google Authenticator."""
    is_valid = TOTPService.verify_totp(request.identifier, request.totp_code)
    
    if is_valid:
        return {"message": "TOTP verified successfully", "verified": True}
    else:
        raise HTTPException(status_code=400, detail="Invalid TOTP code")
